// docs/10.system-design/coding/answers/components/pagination/vue/Pagination.vue
<template>
  <nav class="pager" role="navigation" aria-label="Pagination">
    <button class="pager-btn" :disabled="current===1" @click="go(current-1)" aria-label="上一页">上一页</button>
    <ul class="pager-list" role="list">
      <li v-for="(p,i) in pages" :key="i" :class="p==='...'?'pager-ellipsis':''">
        <template v-if="p==='...'">…</template>
        <button v-else class="pager-page" :class="p===current?'is-current':''" :aria-current="p===current?'page':undefined" @click="go(Number(p))">{{ p }}</button>
      </li>
    </ul>
    <button class="pager-btn" :disabled="current===totalPages" @click="go(current+1)" aria-label="下一页">下一页</button>
  </nav>
</template>

<script setup lang="ts">
  import { computed } from 'vue'
  const props = defineProps<{ total: number; pageSize: number; modelValue: number }>()
  const emit = defineEmits<{ (e:'update:modelValue', v:number): void }>()
  const totalPages = computed(()=> Math.max(1, Math.ceil(props.total / props.pageSize)))
  const current = computed(()=> props.modelValue)
  function go (p:number){ if (p<1 || p>totalPages.value || p===current.value) return; emit('update:modelValue', p) }
  function range (a:number,b:number){ const r:number[]=[]; for(let i=a;i<=b;i++) r.push(i); return r }
  const pages = computed<(number|'...')[]>(()=>{
    if (totalPages.value <= 7) return range(1, totalPages.value)
    const left = Math.max(2, current.value - 1)
    const right = Math.min(totalPages.value - 1, current.value + 1)
    const arr:(number|'...')[] = [1]
    if (left>2) arr.push('...')
    arr.push(...range(left,right))
    if (right<totalPages.value-1) arr.push('...')
    arr.push(totalPages.value)
    return arr
  })
</script>

<style scoped>
  .pager{display:flex;align-items:center;gap:8px}
  .pager-btn{padding:4px 8px}
  .pager-list{display:flex;gap:4px;list-style:none;margin:0;padding:0}
  .pager-page{padding:4px 8px;border:1px solid #d9d9d9;border-radius:4px;background:#fff;cursor:pointer}
  .pager-page.is-current{background:#1677ff;color:#fff;border-color:#1677ff}
  .pager-ellipsis{padding:4px 8px;color:#999}
</style>

// docs/10.system-design/coding/answers/components/pagination/react/Pagination.tsx
import React from 'react'
import './Pagination.css'

interface Props {
  total: number
  pageSize: number
  current: number
  onChange: (page: number) => void
}

function range (start: number, end: number) {
  const arr: number[] = []
  for (let i = start; i <= end; i++) arr.push(i)
  return arr
}

export default function Pagination ({ total, pageSize, current, onChange }: Props) {
  const totalPages = Math.max(1, Math.ceil(total / pageSize))
  const go = (p: number) => { if (p < 1 || p > totalPages || p === current) return; onChange(p) }

  const pages: (number | '...')[] = []
  if (totalPages <= 7) {
    pages.push(...range(1, totalPages))
  } else {
    const left = Math.max(2, current - 1)
    const right = Math.min(totalPages - 1, current + 1)
    pages.push(1)
    if (left > 2) pages.push('...')
    pages.push(...range(left, right))
    if (right < totalPages - 1) pages.push('...')
    pages.push(totalPages)
  }

  return (
    <nav className="pager" role="navigation" aria-label="Pagination">
      <button className="pager-btn" disabled={current === 1} onClick={() => go(current - 1)} aria-label="上一页">上一页</button>
      <ul className="pager-list" role="list">
        {pages.map((p, i) => (
          p === '...'
            ? <li key={`e-${i}`} className="pager-ellipsis" aria-hidden>…</li>
            : <li key={p}>
                <button
                  className={['pager-page', p === current ? 'is-current' : ''].join(' ')}
                  aria-current={p === current ? 'page' : undefined}
                  onClick={() => go(p as number)}
                >{p}</button>
              </li>
        ))}
      </ul>
      <button className="pager-btn" disabled={current === totalPages} onClick={() => go(current + 1)} aria-label="下一页">下一页</button>
    </nav>
  )
}
