// docs/10.system-design/coding/answers/components/modal/vue/ModalApi.tsx
import { reactive, render, Teleport, h, VNode } from 'vue'
import Modal from './Modal.vue'

interface OpenOptions {
   title?: string | (() => string | VNode)
   content?: string | (() => string | VNode)
   onClose?: () => void
   onConfirm?: () => void
   onCancel?: () => void
   confirmText?: string
   cancelText?: string
   closeOnClickMask?: boolean
   container?: HTMLElement
}

function TeleportWrapper (props) {
  return h(Teleport, { to: props.to }, [
    h(Modal, {
      show: props.show,
      confirmText: props.confirmText,
      cancelText: props.cancelText,
      closeOnClickMask: props.closeOnClickMask,
      onClose: props._onClose,
      onConfirm: props._onConfirm,
      onCancel: props._onCancel
    }, {
      title: () => (typeof props.title === 'function' ? props.title() : props.title),
      default: () => (typeof props.content === 'function' ? props.content() : props.content)
    })
  ])
}

export function open (options: OpenOptions) {
  const {
    title,
    content,
    onClose,
    onConfirm,
    onCancel,
    confirmText = '确定',
    cancelText = '取消',
    closeOnClickMask = true,
    container = document.body
  } = options || {}

  const state = reactive({
    to: container,
    show: true,
    title,
    content,
    confirmText,
    cancelText,
    closeOnClickMask,
    _onClose: () => { onClose?.(); dispose() },
    _onConfirm: () => { onConfirm?.(); dispose() },
    _onCancel: () => { onCancel?.(); dispose() }
  })

  const host = document.createElement('div')
  container.appendChild(host)

  const dispose = () => {
    state.show = false
    render(null, host)
    host.remove()
  }

  render(h(TeleportWrapper, state), host)
  return { close: dispose }
}

// docs/10.system-design/coding/answers/components/modal/react/ModalApi.tsx
import React, { useEffect, useRef } from 'react'
import './Modal.css'
import { createRoot, Root } from 'react-dom/client'

interface ModalProps {
   title: () => React.ReactNode
   content: () => React.ReactNode
   onClose: () => void
   onConfirm: () => void
   onCancel: () => void
   confirmText?: string
   cancelText?: string
   closeOnClickMask?: boolean
}

function Modal (props: ModalProps) {
  const { closeOnClickMask = true } = props
  const maskRef = useRef<HTMLDivElement>(null)

  // 让遮罩获取焦点以便监听 Escape
  useEffect(() => {
    maskRef.current?.focus()
  }, [])

  return (
      <div
         ref={maskRef}
         className="modal-mask"
         tabIndex={-1}
         onClick={e => {
           if (!closeOnClickMask) return
           if (e.target === e.currentTarget) props.onClose()
         }}
         onKeyDown={e => {
           if (e.key === 'Escape') props.onClose()
         }}
         aria-hidden={false}
      >
         <div className="modal" role="dialog" aria-modal="true">
            <span
               className="close"
               onClick={props.onClose}
            >
               &times;
            </span>
            <div className="modal-title">
               {props.title()}
            </div>
            <div className="modal-content">
               {props.content()}
            </div>
            <div className="modal-footer">
               <button className="modal-confirm" onClick={props.onConfirm}>
                  {props.confirmText || '确定'}
               </button>
               <button className="modal-cancel" onClick={props.onCancel}>
                  {props.cancelText || '取消'}
               </button>
            </div>
         </div>
      </div>
  )
}

interface OpenOptions {
   title?: React.ReactNode | (() => React.ReactNode)
   content?: React.ReactNode | (() => React.ReactNode)
   onClose?: () => void
   onConfirm?: () => void
   onCancel?: () => void
   confirmText?: string
   cancelText?: string
   closeOnClickMask?: boolean
   container?: HTMLElement
}

// React 18/19 open API
export function open (options: OpenOptions = {}) {
  const {
    title,
    content,
    onClose,
    onConfirm,
    onCancel,
    confirmText = '确定',
    cancelText = '取消',
    closeOnClickMask = true,
    container = document.body
  } = options

  const host = document.createElement('div')
  container.appendChild(host)
  const root: Root = createRoot(host)

  let disposed = false

  const dispose = () => {
    if (disposed) return
    disposed = true
    // 卸载并移除节点
    root.unmount()
    host.remove()
  }

  const _onClose = () => { onClose?.(); dispose() }
  const _onConfirm = () => { onConfirm?.(); dispose() }
  const _onCancel = () => { onCancel?.(); dispose() }

  root.render(
      <Modal
         title={typeof title === 'function' ? title : () => title}
         content={typeof content === 'function' ? content : () => content}
         onClose={_onClose}
         onConfirm={_onConfirm}
         onCancel={_onCancel}
         confirmText={confirmText}
         cancelText={cancelText}
         closeOnClickMask={closeOnClickMask}
      />
  )

  return { close: dispose }
}

export { Modal }
