// docs/10.system-design/coding/answers/components/popover/vue/Popover.vue
<template>
  <>
    <button class="pop-trigger" ref="triggerRef" @click="open=!open" :aria-expanded="open"><slot>打开 Popover</slot></button>
    <div v-if="open" class="popover" ref="popRef" :style="style" role="dialog" aria-modal="false">{{ content }}</div>
  </>
</template>

<script setup lang="ts">
  import { onMounted, onUnmounted, reactive, ref, watch } from 'vue'
  const props = withDefaults(defineProps<{ content: string; placement?: 'top'|'bottom'|'left'|'right' }>(), { placement: 'bottom' })
  const open = ref(false)
  const triggerRef = ref<HTMLElement>()
  const popRef = ref<HTMLElement>()
  const style = reactive<{ top?: string; left?: string }>({})

  function compute(){
    const t = triggerRef.value, p = popRef.value
    if (!t || !p) return
    const tr = t.getBoundingClientRect(), pr = p.getBoundingClientRect()
    let top=0, left=0
    if (props.placement==='bottom'){ top = tr.bottom + 8; left = tr.left + tr.width/2 - pr.width/2 }
    if (props.placement==='top'){ top = tr.top - pr.height - 8; left = tr.left + tr.width/2 - pr.width/2 }
    if (props.placement==='left'){ top = tr.top + tr.height/2 - pr.height/2; left = tr.left - pr.width - 8 }
    if (props.placement==='right'){ top = tr.top + tr.height/2 - pr.height/2; left = tr.right + 8 }
    const vw = window.innerWidth, vh = window.innerHeight
    if (top + pr.height > vh && props.placement==='bottom') top = tr.top - pr.height - 8
    if (top < 0 && props.placement==='top') top = tr.bottom + 8
    if (left + pr.width > vw) left = vw - pr.width - 8
    if (left < 0) left = 8
    style.top = `${top + window.scrollY}px`
    style.left = `${left + window.scrollX}px`
  }

  function onScroll(){ if (open.value) compute() }
  onMounted(()=>{ window.addEventListener('scroll', onScroll, { passive:true }); window.addEventListener('resize', onScroll) })
  onUnmounted(()=>{ window.removeEventListener('scroll', onScroll); window.removeEventListener('resize', onScroll) })
  watch(open, v=>{ if (v) setTimeout(compute) })
</script>

<style scoped>
  .pop-trigger{padding:6px 12px;border:1px solid #d9d9d9;border-radius:6px;background:#fff;cursor:pointer}
  .popover{position:absolute;background:#fff;border:1px solid #d9d9d9;border-radius:6px;box-shadow:0 6px 16px rgba(0,0,0,.08);padding:8px 12px;z-index:1000}
</style>

// docs/10.system-design/coding/answers/components/popover/react/Popover.tsx
import React, { useEffect, useLayoutEffect, useRef, useState } from 'react'
import './Popover.css'

interface Props {
  content: React.ReactNode
  placement?: 'top' | 'bottom' | 'left' | 'right'
}

export default function Popover ({ content, placement = 'bottom', children }: React.PropsWithChildren<Props>) {
  const triggerRef = useRef<HTMLButtonElement>(null)
  const popRef = useRef<HTMLDivElement>(null)
  const [open, setOpen] = useState(false)
  const [style, setStyle] = useState<React.CSSProperties>({})

  function computePosition () {
    const t = triggerRef.current
    const p = popRef.current
    if (!t || !p) return
    const tr = t.getBoundingClientRect()
    const pr = p.getBoundingClientRect()
    let top = 0, left = 0, plc = placement
    if (placement === 'bottom') { top = tr.bottom + 8; left = tr.left + tr.width/2 - pr.width/2 }
    if (placement === 'top') { top = tr.top - pr.height - 8; left = tr.left + tr.width/2 - pr.width/2 }
    if (placement === 'left') { top = tr.top + tr.height/2 - pr.height/2; left = tr.left - pr.width - 8 }
    if (placement === 'right') { top = tr.top + tr.height/2 - pr.height/2; left = tr.right + 8 }
    // simple flip if out of viewport vertically
    const vw = window.innerWidth, vh = window.innerHeight
    if (top + pr.height > vh && placement === 'bottom') { plc = 'top'; top = tr.top - pr.height - 8 }
    if (top < 0 && placement === 'top') { plc = 'bottom'; top = tr.bottom + 8 }
    if (left + pr.width > vw) left = vw - pr.width - 8
    if (left < 0) left = 8
    setStyle({ top: `${top + window.scrollY}px`, left: `${left + window.scrollX}px` })
  }

  useLayoutEffect(() => { if (open) computePosition() }, [open])
  useEffect(() => {
    function onScroll () { if (open) computePosition() }
    window.addEventListener('scroll', onScroll, { passive: true })
    window.addEventListener('resize', onScroll)
    return () => { window.removeEventListener('scroll', onScroll); window.removeEventListener('resize', onScroll) }
  }, [open])

  return (
    <>
      <button className="pop-trigger" ref={triggerRef} onClick={() => setOpen(o => !o)} aria-expanded={open}>{children}</button>
      {open && (
        <div className="popover" ref={popRef} style={style} role="dialog" aria-modal={false}>
          {content}
        </div>
      )}
    </>
  )
}
