// docs/10.system-design/coding/answers/components/tabs/vue/Tabs.vue
<template>
  <div class="tabs">
    <div class="tablist" role="tablist" aria-label="Tabs" @keydown="onKeyDown">
      <button
        v-for="it in items"
        :key="it.key"
        role="tab"
        :aria-selected="it.key===activeKey"
        :tabindex="it.key===activeKey? 0 : -1"
        class="tab"
        :class="it.key===activeKey?'is-active':''"
        @click="activeKey=it.key"
      >{{ it.label }}</button>
    </div>
    <div role="tabpanel" class="tabpanel">
      <component :is="activeItem?.component || 'div'">
        <template v-if="!activeItem?.component">{{ activeItem?.content }}</template>
      </component>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { computed, ref } from 'vue'
  interface TabItem { key: string; label: string; content?: string; component?: any }
  const props = defineProps<{ items: TabItem[]; defaultActiveKey?: string }>()
  const activeKey = ref(props.defaultActiveKey || props.items[0]?.key)
  const activeItem = computed(()=> props.items.find(i=>i.key===activeKey.value))
  function onKeyDown(e: KeyboardEvent){
    const idx = props.items.findIndex(i=>i.key===activeKey.value)
    if (e.key==='ArrowRight') activeKey.value = props.items[(idx+1)%props.items.length].key
    if (e.key==='ArrowLeft') activeKey.value = props.items[(idx-1+props.items.length)%props.items.length].key
    if (e.key==='Home') activeKey.value = props.items[0].key
    if (e.key==='End') activeKey.value = props.items[props.items.length-1].key
  }
</script>

<style scoped>
  .tablist{display:flex;gap:8px;margin-bottom:8px}
  .tab{padding:6px 12px;border:1px solid #d9d9d9;border-radius:6px;background:#fff;cursor:pointer}
  .tab.is-active{background:#1677ff;color:#fff;border-color:#1677ff}
  .tabpanel{border:1px solid #f0f0f0;border-radius:6px;padding:8px}
</style>

// docs/10.system-design/coding/answers/components/tabs/react/Tabs.tsx
import React, { useEffect, useRef, useState } from 'react'
import './Tabs.css'

interface TabItem { key: string; label: string; content: React.ReactNode }

interface Props { items: TabItem[]; defaultActiveKey?: string }

export default function Tabs ({ items, defaultActiveKey }: Props) {
  const [activeKey, setActiveKey] = useState(defaultActiveKey || items[0]?.key)
  const listRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const idx = items.findIndex(i => i.key === activeKey)
    const btn = listRef.current?.querySelectorAll<HTMLButtonElement>('[role=tab]')[idx]
    btn?.focus()
  }, [activeKey, items])

  function onKeyDown (e: React.KeyboardEvent) {
    const tabs = items
    const idx = tabs.findIndex(i => i.key === activeKey)
    if (e.key === 'ArrowRight') setActiveKey(tabs[(idx + 1) % tabs.length].key)
    if (e.key === 'ArrowLeft') setActiveKey(tabs[(idx - 1 + tabs.length) % tabs.length].key)
    if (e.key === 'Home') setActiveKey(tabs[0].key)
    if (e.key === 'End') setActiveKey(tabs[tabs.length - 1].key)
  }

  const active = items.find(i => i.key === activeKey)

  return (
    <div className="tabs">
      <div
        className="tablist"
        role="tablist"
        aria-label="Tabs"
        onKeyDown={onKeyDown}
        ref={listRef}
      >
        {items.map((it, i) => (
          <button
            key={it.key}
            role="tab"
            aria-selected={it.key === activeKey}
            tabIndex={it.key === activeKey ? 0 : -1}
            className={[ 'tab', it.key === activeKey ? 'is-active' : '' ].join(' ')}
            onClick={() => setActiveKey(it.key)}
          >{it.label}</button>
        ))}
      </div>
      <div role="tabpanel" className="tabpanel">{active?.content}</div>
    </div>
  )
}
