// docs/10.system-design/coding/answers/components/upload/vue/Upload.vue
<template>
  <div>
    <div class="u-toolbar">
      <input type="file" multiple @change="onSelect" />
      <button @click="cancelAll">取消全部</button>
    </div>
    <ul class="u-list">
      <li v-for="item in list" :key="item.name" class="u-item">
        <div class="u-row">
          <span class="u-name">{{ item.name }}</span>
          <span class="u-size">{{ Math.round(item.size/1024) }} KB</span>
          <span class="u-status" :class="'u-'+item.status">{{ item.status }}</span>
        </div>
        <div class="u-bar"><span :style="{ width: item.percent + '%' }"/></div>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
  import { reactive } from 'vue'
  interface Item { name: string; size: number; uploaded: number; percent: number; status: 'pending'|'uploading'|'done'|'error'|'canceled' }
  const props = withDefaults(defineProps<{ chunkSize?: number; concurrency?: number }>(), { chunkSize: 256*1024, concurrency: 3 })
  const list = reactive<Item[]>([])
  const abort = reactive({ canceled: false })

  function simulateUploadChunk (file: File, start: number, end: number) {
    return new Promise<void>(resolve => setTimeout(resolve, 60 + Math.random()*140))
  }

  async function uploadFile (file: File) {
    const total = file.size
    const name = file.name
    let item = list.find(i=>i.name===name)
    if (!item) { item = { name, size: total, uploaded:0, percent:0, status:'uploading' }; list.push(item) }

    const chunks: Array<[number, number]> = []
    for (let start = 0; start < total; start += props.chunkSize) chunks.push([start, Math.min(start+props.chunkSize, total)])

    let uploaded = 0
    let cursor = 0
    async function worker(){
      while (cursor < chunks.length && !abort.canceled){
        const [start, end] = chunks[cursor++]
        await simulateUploadChunk(file, start, end)
        uploaded += (end - start)
        item!.uploaded = uploaded
        item!.percent = Math.min(100, Math.round(uploaded/total*100))
      }
    }
    const workers = Array.from({ length: Math.min(props.concurrency, chunks.length) }, ()=>worker())
    await Promise.all(workers)
    if (abort.canceled) { item!.status='canceled'; return }
    item!.status='done'; item!.percent=100; item!.uploaded=total
  }

  function onSelect (e: Event){
    const input = e.target as HTMLInputElement
    if (!input.files || !input.files.length) return
    abort.canceled = false
    Array.from(input.files).forEach(uploadFile)
    input.value = ''
  }

  function cancelAll(){ abort.canceled = true }
</script>

<style scoped>
  .u-toolbar{display:flex;gap:8px;align-items:center;margin-bottom:8px}
  .u-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:8px}
  .u-item{border:1px solid #d9d9d9;border-radius:6px;padding:8px}
  .u-row{display:flex;gap:12px;align-items:center;justify-content:space-between}
  .u-bar{height:6px;background:#f5f5f5;border-radius:3px;overflow:hidden;margin-top:6px}
  .u-bar>span{display:block;height:100%;background:#1677ff}
  .u-status{font-size:12px}
  .u-done{color:#52c41a}.u-error{color:#ff4d4f}.u-canceled{color:#999}
</style>

// docs/10.system-design/coding/answers/components/upload/react/Upload.tsx
import React, { useMemo, useRef, useState } from 'react'
import './Upload.css'

interface Props {
  chunkSize?: number
  concurrency?: number
}

interface ProgressItem {
  name: string
  size: number
  uploaded: number
  percent: number
  status: 'pending' | 'uploading' | 'done' | 'error' | 'canceled'
}

export default function Upload ({ chunkSize = 256 * 1024, concurrency = 3 }: Props) {
  const [list, setList] = useState<ProgressItem[]>([])
  const abortRef = useRef<{ canceled: boolean }>({ canceled: false })

  function simulateUploadChunk (file: File, start: number, end: number) {
    // simulate network delay per chunk
    return new Promise<void>((resolve) => {
      const duration = 60 + Math.random() * 140
      setTimeout(() => resolve(), duration)
    })
  }

  async function uploadFile (file: File) {
    const total = file.size
    const name = file.name
    const item: ProgressItem = { name, size: total, uploaded: 0, percent: 0, status: 'uploading' }
    setList(prev => [...prev.filter(i => i.name !== name), item])

    const chunks: Array<[number, number]> = []
    for (let start = 0; start < total; start += chunkSize) {
      const end = Math.min(start + chunkSize, total)
      chunks.push([start, end])
    }

    let uploaded = 0
    let cursor = 0

    async function worker () {
      while (cursor < chunks.length && !abortRef.current.canceled) {
        const [start, end] = chunks[cursor++]
        await simulateUploadChunk(file, start, end)
        uploaded += (end - start)
        const percent = Math.min(100, Math.round((uploaded / total) * 100))
        setList(prev => prev.map(i => i.name === name ? { ...i, uploaded, percent } : i))
      }
    }

    const workers = Array.from({ length: Math.min(concurrency, chunks.length) }, () => worker())
    await Promise.all(workers)

    if (abortRef.current.canceled) {
      setList(prev => prev.map(i => i.name === name ? { ...i, status: 'canceled' } : i))
      return
    }
    setList(prev => prev.map(i => i.name === name ? { ...i, status: 'done', percent: 100, uploaded: total } : i))
  }

  function onSelect (e: React.ChangeEvent<HTMLInputElement>) {
    const files = e.target.files
    if (!files || !files.length) return
    abortRef.current.canceled = false
    Array.from(files).forEach(uploadFile)
    e.currentTarget.value = ''
  }

  function cancelAll () {
    abortRef.current.canceled = true
  }

  return (
    <div>
      <div className="u-toolbar">
        <input type="file" multiple onChange={onSelect} />
        <button onClick={cancelAll}>取消全部</button>
      </div>
      <ul className="u-list">
        {list.map(item => (
          <li key={item.name} className="u-item">
            <div className="u-row">
              <span className="u-name">{item.name}</span>
              <span className="u-size">{Math.round(item.size/1024)} KB</span>
              <span className={`u-status u-${item.status}`}>{item.status}</span>
            </div>
            <div className="u-bar"><span style={{ width: `${item.percent}%` }} /></div>
          </li>
        ))}
      </ul>
    </div>
  )
}
