// docs/10.system-design/coding/answers/components/form/vue/App.vue
<template>
  <form @submit.prevent="onSubmit">
    <div>
      <label>姓名</label>
      <input :aria-invalid="!!errors.name" :value="values.name || ''" @input="e => setValue('name', e.target.value)" />
      <span v-if="errors.name" role="alert">{{ errors.name }}</span>
    </div>
    <div>
      <label>邮箱</label>
      <input :aria-invalid="!!errors.mail" :value="values.mail || ''" @input="e => setValue('mail', e.target.value)" />
      <span v-if="errors.mail" role="alert">{{ errors.mail }}</span>
    </div>
    <button type="submit">提交</button>
  </form>
</template>

<script setup lang="ts">
  import { useForm, required, email } from './useForm'
  const { values, errors, setValue, validate } = useForm({ name: '', mail: '' }, { name: [required()], mail: [required(), email()] })
  function onSubmit(){ validate().then(ok => console.log('valid:', ok, values, errors)) }
</script>

// docs/10.system-design/coding/answers/components/form/react/App.tsx
import React from 'react'
import { useForm, required, email } from './useForm'

function App () {
  const form = useForm({ name: '', mail: '' }, {
    name: [required()],
    mail: [required(), email()]
  })

  return (
    <form onSubmit={async e => { e.preventDefault(); const ok = await form.validate(); console.log('valid:', ok, form.values, form.errors) }}>
      <div>
        <label>姓名</label>
        <input aria-invalid={!!form.errors.name} value={form.values.name || ''} onChange={e => form.setValue('name', e.target.value)} />
        {form.errors.name && <span role="alert">{form.errors.name}</span>}
      </div>
      <div>
        <label>邮箱</label>
        <input aria-invalid={!!form.errors.mail} value={form.values.mail || ''} onChange={e => form.setValue('mail', e.target.value)} />
        {form.errors.mail && <span role="alert">{form.errors.mail}</span>}
      </div>
      <button type="submit">提交</button>
    </form>
  )
}

export default App
